service:
  whether-api:
    baseUrl: "https://api.openweathermap.org/data/2.5/"
    currentWhether: "weather"
    forecastWhether: "forecast"
    readTimeoutMs: 5000
    connectTimeoutMs: 5000
    apiKey: "730453e479daeafcc36e16283cadacf8"


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/weather_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  show-sql: true
  properties:
    hibernate:
      format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG

tolerence: 600